services:
  postgres:
    image: postgres
    container_name: sbms-postgres-data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root # Cambiar si se despliega a produccion!!!
      POSTGRES_DB: sbms_db
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:latest
    container_name: sbms-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: root # Cambiar si se despliega a produccion!!!
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  redis:
    image: redis:7.4-alpine
    container_name: sbms-redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  
    
volumes:
  postgres-data:
    external: true
    name: postgres-data
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  redis_data:
    driver: local