spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_SECURITY_SERVICE_OAUTH:http://localhost:9000/oauth2/jwks}
  application:
    name: sbms-gateway-service
server:
  port: ${SERVER_PORT:8080}
  microservices:
    customer-service-url: ${CUSTOMER_SERVICE_URL:http://localhost:8083}
    account-service-url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
    credit-disbursement-service-url: ${CREDIT_DISBURSEMENT_SERVICE_URL:http://localhost:8082}