spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_SECURITY_SERVICE_OAUTH:http://localhost:9000/oauth2/jwks}
  application:
    name: sbms-gateway-service
server:
  port: ${SERVER_PORT:8080}
  microservices:
    customer-service-url: ${CUSTOMER_SERVICE_URL:http://localhost:8083}
    account-service-url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
    credit-disbursement-service-url: ${CREDIT_DISBURSEMENT_SERVICE_URL:http://localhost:8082}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Customer Service
        url: /v3/api-docs/customers
      - name: Account Service
        url: /v3/api-docs/accounts
      - name: Credit Disbursement Service
        url: /v3/api-docs/credit-disbursements
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
