spring:
  application:
    name: sbms-credit-disbursement-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sbms_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root} # Establecer en variable de entorno si se corre en producción!!!
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    username: ${MQ_USERNAME:rabbitmq}
    password: ${MQ_PASSWORD:root} # Establecer en variable de entorno si se corre en producción!!!
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
server:
  port: ${SERVER_PORT:8082}
rabbitmq:
  queue: sms_notification
  exchange: sms_exchange
  routingkey: sms_routingkey
feign:
  client:
    account:
      name: account-service
      url: http://localhost:8081/accounts
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs