version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres-data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sbms_db
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - '5432:5432'
volumes:
  postgres-data:
    external: true
    name: postgres-data